[package]
name = "novade-domain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
novade-core = { path = "../novade-core" }
# Weitere dom채nenspezifische Abh채ngigkeiten sp채ter hinzuf체gen
